export type Property = { slug:string; name:string; location:string; type:string; bedrooms:string; area:string; price:string; status:string; image:string; description:string; amenities:string[] }
export type Location = { slug:string; name:string; description:string; positioning:string; price:string; image:string; advantages:string[] }
export type Article = { slug:string; title:string; category:string; excerpt:string; image:string; date:string }
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`
export const properties: Property[] = [
 {slug:'skyline-heights-whitefield',name:'Skyline Heights',location:'Whitefield, Bengaluru',type:'Apartment',bedrooms:'3 BHK',area:'1,850 sq.ft.',price:'₹1.45 Cr',status:'Ready to move',image:img('photo-1600607687920-4e2a09cf159d'),description:'A light-filled contemporary residence close to Whitefield’s work and lifestyle hubs.',amenities:['Clubhouse','Pool','Gym','24/7 security']},
 {slug:'greenwood-residences-sarjapur',name:'Greenwood Residences',location:'Sarjapur Road, Bengaluru',type:'Apartment',bedrooms:'2 & 3 BHK',area:'1,450–2,100 sq.ft.',price:'₹98 Lakh onwards',status:'Under construction',image:img('photo-1600566753190-17f0baa2a6c3'),description:'Thoughtfully planned family homes with generous greens and everyday convenience.',amenities:['Landscaped gardens','Co-working lounge','Kids play area','EV charging']},
 {slug:'oakwood-villas-devanahalli',name:'Oakwood Villas',location:'Devanahalli, Bengaluru',type:'Villa',bedrooms:'4 BHK',area:'2,800 sq.ft.',price:'₹2.25 Cr',status:'New launch',image:img('photo-1600585154340-be6161a56a0c'),description:'Private villa living with expansive proportions and long-term North Bengaluru potential.',amenities:['Private garden','Terrace','Gated community','Clubhouse']},
 {slug:'lakeview-greens-hebbal',name:'Lakeview Greens',location:'Hebbal, Bengaluru',type:'Apartment',bedrooms:'3 BHK',area:'1,720 sq.ft.',price:'₹1.68 Cr',status:'Ready to move',image:img('photo-1600607688969-a5bfcd646154'),description:'Established neighbourhood living with effortless airport and central city access.',amenities:['Lake views','Gym','Concierge','Sports courts']}
]
export const locations: Location[] = [
 {slug:'whitefield',name:'Whitefield',description:'Tech-driven living with everything within reach.',positioning:'A mature employment and lifestyle destination for professionals and growing families.',price:'₹90 Lakh – ₹3 Cr+',image:img('photo-1518005020951-eccb494ad742'),advantages:['ITPL and major tech campuses','Metro connectivity','International schools','Retail and dining']},
 {slug:'sarjapur-road',name:'Sarjapur Road',description:'Fast-growing, well-connected and full of promise.',positioning:'A high-demand corridor balancing new communities, schools and future infrastructure.',price:'₹75 Lakh – ₹2.5 Cr',image:img('photo-1564013799919-ab600027ffc6'),advantages:['Strong rental demand','New gated communities','Schools and hospitals','Outer Ring Road access']},
 {slug:'electronic-city',name:'Electronic City',description:'Smart homes and smart value for modern families.',positioning:'A practical value-led market with excellent access to Bengaluru’s southern employment hubs.',price:'₹55 Lakh – ₹1.8 Cr',image:img('photo-1600607687939-ce8a6c25118c'),advantages:['Metro and expressway access','Value-focused inventory','Established tech ecosystem','Family amenities']},
 {slug:'hebbal',name:'Hebbal',description:'Established neighbourhoods with effortless access.',positioning:'A premium north Bengaluru address for buyers who value connectivity and established infrastructure.',price:'₹1.2 Cr – ₹4 Cr+',image:img('photo-1600566753086-00f18fb6b3ea'),advantages:['Airport Road access','Business districts nearby','Healthcare and schools','Established social infrastructure']},
 {slug:'devanahalli',name:'Devanahalli',description:'Expansive villa living with long-term potential.',positioning:'North Bengaluru’s growth story, suited to patient investors and spacious family living.',price:'₹70 Lakh – ₹3 Cr+',image:img('photo-1605146769289-440113cc3d00'),advantages:['Kempegowda airport','Planned infrastructure','Villa communities','Investment upside']},
 {slug:'north-bengaluru',name:'North Bengaluru',description:'The city’s next chapter, closer to the airport.',positioning:'A broad growth belt with new business districts, infrastructure and modern residential options.',price:'₹80 Lakh – ₹3.5 Cr+',image:img('photo-1600607687920-4e2a09cf159d'),advantages:['Airport connectivity','Emerging commercial hubs','Large-format projects','Long-term growth']}
]
export const articles: Article[] = [
 {slug:'best-areas-to-buy-home-in-bengaluru-2026',title:'Best Areas to Buy a Home in Bengaluru in 2026',category:'Buying guide',excerpt:'A practical way to compare connectivity, lifestyle and long-term value across Bengaluru’s key corridors.',image:img('photo-1600607687920-4e2a09cf159d'),date:'Jan 12, 2026'},
 {slug:'whitefield-vs-sarjapur-road',title:'Whitefield vs Sarjapur Road: Which Is Better for Homebuyers?',category:'Locations',excerpt:'Two of Bengaluru’s most searched corridors, compared for commute, community and investment.',image:img('photo-1564013799919-ab600027ffc6'),date:'Dec 04, 2025'},
 {slug:'things-to-check-before-buying-an-apartment',title:'Things to Check Before Buying an Apartment',category:'Due diligence',excerpt:'The questions that help first-time buyers move from excitement to a confident decision.',image:img('photo-1600566753190-17f0baa2a6c3'),date:'Nov 18, 2025'},
 {slug:'is-north-bengaluru-a-good-investment',title:'Is North Bengaluru a Good Investment?',category:'Investment',excerpt:'Understanding the infrastructure story and what it means for different investor profiles.',image:img('photo-1600585154340-be6161a56a0c'),date:'Oct 22, 2025'}
]
export const getProperty=(slug:string)=>properties.find(p=>p.slug===slug)
export const getLocation=(slug:string)=>locations.find(l=>l.slug===slug)
export const getArticle=(slug:string)=>articles.find(a=>a.slug===slug)
